---
code: UNNECESSARY_SET_OPERATOR
count: 0
config:
  diagnostics:
    UNNECESSARY_SET_OPERATOR:
      enabled: false
---
Version: '2012-10-17'
Statement:
  - Effect: Allow
    Action: kms:Decrypt
    Resource: '*'
    Condition:
      ForAllValues:StringEquals:
        kms:RequestAlias: alias/example
