---
code: UNRECOGNIZED_CONDITION_KEY
count: 0
config:
  diagnostics:
    UNRECOGNIZED_CONDITION_KEY:
      enabled: false
---
Version: '2012-10-17'
Statement:
  - Effect: Allow
    Action: kms:Decrypt
    Resource: '*'
    Condition:
      StringEquals:
        kms:NotARealConditionKey: alias/example
