---
exact: true
includes:
  - Sid
  - Action
  - NotAction
  - Resource
  - NotResource
  - Condition
  - Principal
  - NotPrincipal
---
Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Action: '*'
            Resource: '*'
          - Effect: Allow
            $0
